# Configurations for the Speaker Embedding Pipeline


# need to be updated for the current directory of the project for current 
CURRENT_DIR: C:\Users\USER\source\repos\vcuxvdsuk\graduation-project


# Audio file to process
embedding_output_file: "${CURRENT_DIR}/Arabic/embedding"
train_audio_list_file: "${CURRENT_DIR}/Arabic/families.csv"
test_audio_list_file: "${CURRENT_DIR}/Arabic/families_test.csv"
audio_dir: "${CURRENT_DIR}/Arabic/combined_voice_dir"
familes_emb: "${CURRENT_DIR}/Arabic/familes_emb.csv"

# ECAPA-TDNN model configuration
speechbrain_model:
  ASR: "speechbrain/asr-crdnn-rnnlm-librispeech"
  arabic_embedding: "speechbrain/spkrec-xvect-voxsrc"
  ecapa: "speechbrain/spkrec-ecapa-voxceleb"  # Model source on SpeechBrain
  savedir: "models_dir"  # Directory where the model will be saved locally

# PCA settings for dimensionality reduction
pca:
  n_components: 2  # Number of components for PCA (2D for plotting)

# Embedding modification settings
modification:
  noise_mean: 0  # Mean of the normal noise distribution
  noise_std: 0.1  # Standard deviation of the normal noise distribution

# Speaker Verification settings
verification:
  threshold: 0.5  # Cosine similarity threshold for determining if two embeddings are from the same speaker

# Plotting settings
plotting:
  title: "Speaker Embedding Plot"  # Title of the embedding plot
  xlabel: "PCA Component 1"  # Label for the X-axis
  ylabel: "PCA Component 2"  # Label for the Y-axis