# Configurations for the Speaker Embedding Pipeline


# need to be updated for the current directory of the project for current

###CURRENT_DIR: C:\Users\USER\source\repos\vcuxvdsuk\graduation-project

# Audio file to process
embedding_output_file: "/app/Arabic/embedding"
train_audio_list_file: "/app/Arabic/families.csv"
test_audio_list_file: "/app/Arabic/families_test.csv"
audio_dir: "/app/Arabic/combined_voice_dir"
all_samples: "/app/Arabic/combined.csv"
familes_emb: "/app/Arabic/familes_emb.csv"
familes_re_emb: "/app/Arabic/familes_re_emb.csv"
familes_labels: "/app/Arabic/familes_labels/familes_labels_round_" #adding number and then .csv in the pipline
familes_plot_path: "/app/test_emb_plots/new_sample_embeddings_plot_family_"

# ECAPA-TDNN model configuration
speechbrain_model:
  ASR: "speechbrain/asr-crdnn-rnnlm-librispeech"
  arabic_embedding: "speechbrain/spkrec-xvect-voxsrc"
  ecapa: "speechbrain/spkrec-ecapa-voxceleb"  # Model source on SpeechBrain
  savedir: "/app/models_dir"  # Directory where the model will be saved locally

# PCA settings for dimensionality reduction
pca:
  n_components: 2  # Number of components for PCA (2D for plotting)

adaptation:
  num_epochs: 50  # Number of epochs for adaptation
  batch_size: 16
  train_nums_of_families: 40 #out of 50 families
  epochs_per_family: 2 
  load_localy_saved: True  # use the locally saved and fine tune model

# Speaker Verification settings
verification:
  threshold: 0.5  # Cosine similarity threshold for determining if two embeddings are from the same speaker

# Plotting settings
plotting:
  title: "Speaker Embedding Plot"  # Title of the embedding plot
  xlabel: "PCA Component 1"  # Label for the X-axis
  ylabel: "PCA Component 2"  # Label for the Y-axis